/* =========================================================
   File: 07_load_dw.sql
   Purpose: Load dimensions and fact table from raw schema
   Project: Instacart Business Analytics Project

   Design notes:
   - All loads run inside a single transaction. If anything
     fails, the entire DW is rolled back to empty rather than
     left in a half-loaded state.
   - Load ORDER is dictated by FK dependencies:
       department, aisle, user  → independent, load first
       product                  → needs aisle + department
       order                    → needs user
       fact                     → needs order + product + user
   - TRUNCATE order is the REVERSE of load order: fact first,
     because dims can't be truncated while the fact still
     references them (FKs would block it).
   - Dim loads that reference other dims JOIN to those dims
     to translate natural keys (xxx_id) into surrogate keys
     (xxx_key). This is the core surrogate-key pattern.
   - Fact load assumes file 03's view has been updated to
     include user_id (denormalised in from raw.orders), so
     we don't need a separate join to raw.orders here.
   ========================================================= */

USE InstacartBA;
GO

BEGIN TRY
    BEGIN TRANSACTION;
    ALTER TABLE dw.fact_order_item DROP CONSTRAINT FK_fact_order_item_order;
    ALTER TABLE dw.fact_order_item DROP CONSTRAINT FK_fact_order_item_product;
    ALTER TABLE dw.fact_order_item DROP CONSTRAINT FK_fact_order_item_user;
    ALTER TABLE dw.dim_product     DROP CONSTRAINT FK_dim_product_aisle;
    ALTER TABLE dw.dim_product     DROP CONSTRAINT FK_dim_product_department;
    ALTER TABLE dw.dim_order       DROP CONSTRAINT FK_dim_order_user;
     
     /* -----------------------------
       Truncate now that FKs are dropped.
       ----------------------------- */
    TRUNCATE TABLE dw.fact_order_item;
    TRUNCATE TABLE dw.dim_order;
    TRUNCATE TABLE dw.dim_product;
    TRUNCATE TABLE dw.dim_user;
    TRUNCATE TABLE dw.dim_aisle;
    TRUNCATE TABLE dw.dim_department;
    /* =========================================================
       1) dim_department
       - References nothing. Straight copy from raw.
       - department_key is generated by IDENTITY automatically;
         we don't insert it.
       ========================================================= */
    INSERT INTO dw.dim_department (department_id, department_name)
    SELECT
        department_id,
        department
    FROM raw.departments;

    /* =========================================================
       2) dim_aisle
       - References nothing. Same shape as dim_department.
       ========================================================= */
    INSERT INTO dw.dim_aisle (aisle_id, aisle_name)
    SELECT
        aisle_id,
        aisle
    FROM raw.aisles;

    /* =========================================================
       3) dim_user
       - References nothing. DISTINCT because raw.orders has
         many rows per user (one per order), but dim_user
         needs one row per user.
       ========================================================= */
    INSERT INTO dw.dim_user (user_id)
    SELECT DISTINCT
        user_id
    FROM raw.orders;

    /* =========================================================
       4) dim_product
       - References dim_aisle and dim_department.
       - Start FROM raw.products (the source of truth for the
         row count), then JOIN to the already-loaded dims to
         translate aisle_id -> aisle_key, department_id ->
         department_key.
       - INNER JOIN is intentional: if a product points at a
         missing aisle or department, we want the load to
         fail loudly — that's a data quality issue worth
         catching, not silently dropping rows.
       ========================================================= */
    INSERT INTO dw.dim_product (product_id, product_name, aisle_key, department_key)
    SELECT
        p.product_id,
        p.product_name,
        da.aisle_key,
        dd.department_key
    FROM raw.products p
    JOIN dw.dim_aisle      da ON p.aisle_id      = da.aisle_id
    JOIN dw.dim_department dd ON p.department_id = dd.department_id;

    /* =========================================================
       5) dim_order
       - References dim_user. Translate user_id -> user_key.
       - Everything else is a straight copy from raw.orders.
       ========================================================= */
    INSERT INTO dw.dim_order (
        order_id,
        user_key,
        eval_set,
        order_number,
        order_dow,
        order_hour_of_day,
        days_since_prior_order
    )
    SELECT
        o.order_id,
        du.user_key,
        o.eval_set,
        o.order_number,
        o.order_dow,
        o.order_hour_of_day,
        o.days_since_prior_order
    FROM raw.orders o
    JOIN dw.dim_user du ON o.user_id = du.user_id;

    /* =========================================================
       6) fact_order_item
       - Grain: one row per product per order.
       - References dim_order, dim_product, dim_user — three
         surrogate-key lookups.
       - Source is raw.v_order_products_all (the union of
         prior + train), which we updated in file 03 to
         include user_id directly. No more join to raw.orders.
       - order_id is kept as a degenerate dimension on the fact
         (lets us count distinct orders without joining
         dim_order in the business queries).
       - This is the most join-heavy query in the project.
         That's expected and correct for a star-schema load.
       ========================================================= */
    INSERT INTO dw.fact_order_item (
        order_key,
        product_key,
        user_key,
        order_id,
        add_to_cart_order,
        reordered,
        source_table
    )
    SELECT
        do_.order_key,
        dp.product_key,
        du.user_key,
        v.order_id,
        v.add_to_cart_order,
        v.reordered,
        v.source_table
    FROM raw.v_order_products_all v
    JOIN dw.dim_order   do_ ON v.order_id   = do_.order_id
    JOIN dw.dim_product dp  ON v.product_id = dp.product_id
    JOIN dw.dim_user    du  ON v.user_id    = du.user_id;
    /* Note on the alias 'do_': "do" is a reserved-ish word in
       T-SQL contexts (WHILE...DO etc.). Adding the underscore
       avoids any parser surprises. You'll see this convention
       in production code. */
    ALTER TABLE dw.dim_order
    WITH CHECK ADD CONSTRAINT FK_dim_order_user
    FOREIGN KEY (user_key) REFERENCES dw.dim_user(user_key);

    ALTER TABLE dw.dim_product
    WITH CHECK ADD CONSTRAINT FK_dim_product_aisle
    FOREIGN KEY (aisle_key) REFERENCES dw.dim_aisle(aisle_key);

    ALTER TABLE dw.dim_product
    WITH CHECK ADD CONSTRAINT FK_dim_product_department
    FOREIGN KEY (department_key) REFERENCES dw.dim_department(department_key);

    ALTER TABLE dw.fact_order_item
    WITH CHECK ADD CONSTRAINT FK_fact_order_item_order
    FOREIGN KEY (order_key) REFERENCES dw.dim_order(order_key);

    ALTER TABLE dw.fact_order_item
    WITH CHECK ADD CONSTRAINT FK_fact_order_item_product
    FOREIGN KEY (product_key) REFERENCES dw.dim_product(product_key);

    ALTER TABLE dw.fact_order_item
    WITH CHECK ADD CONSTRAINT FK_fact_order_item_user
    FOREIGN KEY (user_key) REFERENCES dw.dim_user(user_key);

   COMMIT TRANSACTION;

/* Capture row counts into variables so PRINT can use them.
   PRINT only accepts scalar expressions, not subqueries. */
DECLARE
    @cnt_dept    INT,
    @cnt_aisle   INT,
    @cnt_user    INT,
    @cnt_product INT,
    @cnt_order   INT,
    @cnt_fact    BIGINT;

SELECT @cnt_dept    = COUNT(*) FROM dw.dim_department;
SELECT @cnt_aisle   = COUNT(*) FROM dw.dim_aisle;
SELECT @cnt_user    = COUNT(*) FROM dw.dim_user;
SELECT @cnt_product = COUNT(*) FROM dw.dim_product;
SELECT @cnt_order   = COUNT(*) FROM dw.dim_order;
SELECT @cnt_fact    = COUNT_BIG(*) FROM dw.fact_order_item;

PRINT 'Load complete.';
PRINT 'dim_department:  ' + CAST(@cnt_dept    AS VARCHAR(20));
PRINT 'dim_aisle:       ' + CAST(@cnt_aisle   AS VARCHAR(20));
PRINT 'dim_user:        ' + CAST(@cnt_user    AS VARCHAR(20));
PRINT 'dim_product:     ' + CAST(@cnt_product AS VARCHAR(20));
PRINT 'dim_order:       ' + CAST(@cnt_order   AS VARCHAR(20));
PRINT 'fact_order_item: ' + CAST(@cnt_fact    AS VARCHAR(20));

END TRY
BEGIN CATCH
    /* If any statement above failed, roll back the entire
       transaction. The DW is left empty (TRUNCATE was inside
       the transaction too, so even the truncate is undone). */
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    /* Re-throw the original error. Without THROW, the CATCH
       block silently swallows the error and the script
       appears to succeed — exactly the wrong outcome. */
    THROW;
END CATCH;
GO